services:
  project_name:
    build: .
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=change_password
      - DB_NAME=words
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=change_password
      - POSTGRES_DB=words
    volumes:
    - "database-data:/var/lib/postgresql/data"
    restart: always
volumes:
  database-data: {}

