FROM golang:1.19-alpine as builder

ENV APP /go/src/project_name

WORKDIR "$APP_HOME"
COPY ../ .
RUN go mod download
RUN go mod verify
RUN go build -o project_name


FROM golang:1.19-alpine

ENV APP /go/src/project_name
RUN mkdir -p "$APP_HOME"
WORKDIR "$APP_HOME"

COPY --from=builder "$APP_HOME"/mathapp $APP_HOME

EXPOSE 8080

CMD ["./project_name"]